### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Ziolo99** [FoxDenStudio/FoxGuard#105]
I know I installed other mods, I'm using spongeforge and something can be incompatibile but look at this crash report please

---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod (spongeforge-1.12.2-forge.jar)
  MovingWorldCore (MovingWorld-Mod-1.12.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 17.07.18 14:04
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from FoxGuard (foxguard)
Caused by: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: Lnet/minecrell/mcstats/SpongeStatsLite;
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2215)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153)
	at com.google.inject.internal.FailableCache.get(FailableCache.java:48)
	at com.google.inject.internal.ConstructorInjectorStore.get(ConstructorInjectorStore.java:50)
	at com.google.inject.internal.ConstructorBindingImpl.initialize(ConstructorBindingImpl.java:138)
	at com.google.inject.internal.InjectorImpl.initializeBinding(InjectorImpl.java:536)
	at com.google.inject.internal.AbstractBindingProcessor$Processor$1.run(AbstractBindingProcessor.java:160)
	at com.google.inject.internal.ProcessedBindingData.initializeBindings(ProcessedBindingData.java:44)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:123)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:232)
	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:236)
	at org.spongepowered.mod.plugin.SpongeModPluginContainer.constructMod(SpongeModPluginContainer.java:282)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:278)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:256)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:560)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:568)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:97)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:332)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: Lnet/minecrell/mcstats/SpongeStatsLite;
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2215)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153)
	at com.google.inject.internal.FailableCache.get(FailableCache.java:48)
	at com.google.inject.internal.MembersInjectorStore.get(MembersInjectorStore.java:68)
	at com.google.inject.internal.ConstructorInjectorStore.createConstructor(ConstructorInjectorStore.java:75)
	at com.google.inject.internal.ConstructorInjectorStore.access$000(ConstructorInjectorStore.java:29)
	at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:37)
	at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:33)
	at com.google.inject.internal.FailableCache$1.load(FailableCache.java:37)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
	... 47 more
Caused by: java.lang.NoClassDefFoundError: Lnet/minecrell/mcstats/SpongeStatsLite;
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getDeclaredFields(Class.java:1916)
	at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:675)
	at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:380)
	at com.google.inject.internal.MembersInjectorStore.createWithListeners(MembersInjectorStore.java:93)
	at com.google.inject.internal.MembersInjectorStore.access$000(MembersInjectorStore.java:37)
	at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:45)
	at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:42)
	at com.google.inject.internal.FailableCache$1.load(FailableCache.java:37)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
	... 62 more
Caused by: java.lang.ClassNotFoundException: net.minecrell.mcstats.SpongeStatsLite
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 76 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zjg000(MinecraftServer.java:3987)

-- Sponge PhaseTracker --
Details:
	Cause Stack: [Empty stack]
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zjg000(MinecraftServer.java:3987)
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:887)
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:370)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:556)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.9.0-5-amd64
	Java Version: 1.8.0_151, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 577728304 bytes (550 MB) / 1051721728 bytes (1003 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 2 total; -Xmx6144M -Xms256M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.2.2611 34 mods loaded, 34 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                           | Version                     | Source                                | Signature                                |
	|:----- |:-------------------------------------------- |:--------------------------- |:------------------------------------- |:---------------------------------------- |
	| UC    | minecraft                                    | 1.12.2                      | minecraft.jar                         | None                                     |
	| UC    | mcp                                          | 9.42                        | minecraft.jar                         | None                                     |
	| UC    | FML                                          | 8.0.99.99                   | minecraft_server.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | forge                                        | 14.23.2.2611                | minecraft_server.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | com.elytradev.movingworld.common.asm.coremod |                             | minecraft.jar                         | None                                     |
	| UC    | spongeapi                                    | 7.1.0-SNAPSHOT-06016f2      | spongeforge-1.12.2-forge.jar          | None                                     |
	| UC    | sponge                                       | 1.12.2-2611-7.1.0-BETA-2990 | spongeforge-1.12.2-forge.jar          | None                                     |
	| UC    | battletowers                                 | 1.6.1                       | BattleTowers-Mod-1.12.2.jar           | None                                     |
	| UC    | baubles                                      | 1.5.2                       | Baubles-1.12-1.5.2.jar                | None                                     |
	| UC    | customnpcs                                   | 1.12                        | CustomNPCs_1.12.2(09jul18).jar        | None                                     |
	| UC    | movingworld                                  | 1.12-6.342                  | MovingWorld-Mod-1.12.jar              | None                                     |
	| UC    | davincisvessels                              | @DVESSELSVER@               | Davincis-Vessels-Mod-1.12.jar         | None                                     |
	| UC    | ic2                                          | 2.8.70-ex112                | industrialcraft-1.12.2-forge.jar      | de041f9f6187debbc77034a344134053277aa3b0 |
	| UC    | ironchest                                    | 1.12.2-7.0.40.824           | Iron-Chests-Mod-1.12.2.jar            | None                                     |
	| UC    | lycanitesmobs                                | 1.17.1.4 - MC 1.12.2        | Lycanites-Mobs-Mod-1.12.2.jar         | None                                     |
	| UC    | arcticmobs                                   | 1.17.1.4 - MC 1.12.2        | Lycanites-Mobs-Mod-1.12.2.jar         | None                                     |
	| UC    | demonmobs                                    | 1.17.1.4 - MC 1.12.2        | Lycanites-Mobs-Mod-1.12.2.jar         | None                                     |
	| UC    | desertmobs                                   | 1.17.1.4 - MC 1.12.2        | Lycanites-Mobs-Mod-1.12.2.jar         | None                                     |
	| UC    | forestmobs                                   | 1.17.1.4 - MC 1.12.2        | Lycanites-Mobs-Mod-1.12.2.jar         | None                                     |
	| UC    | freshwatermobs                               | 1.17.1.4 - MC 1.12.2        | Lycanites-Mobs-Mod-1.12.2.jar         | None                                     |
	| UC    | infernomobs                                  | 1.17.1.4 - MC 1.12.2        | Lycanites-Mobs-Mod-1.12.2.jar         | None                                     |
	| UC    | junglemobs                                   | 1.17.1.4 - MC 1.12.2        | Lycanites-Mobs-Mod-1.12.2.jar         | None                                     |
	| UC    | mountainmobs                                 | 1.17.1.4 - MC 1.12.2        | Lycanites-Mobs-Mod-1.12.2.jar         | None                                     |
	| UC    | plainsmobs                                   | 1.17.1.4 - MC 1.12.2        | Lycanites-Mobs-Mod-1.12.2.jar         | None                                     |
	| UC    | saltwatermobs                                | 1.17.1.4 - MC 1.12.2        | Lycanites-Mobs-Mod-1.12.2.jar         | None                                     |
	| UC    | shadowmobs                                   | 1.17.1.4 - MC 1.12.2        | Lycanites-Mobs-Mod-1.12.2.jar         | None                                     |
	| UC    | swampmobs                                    | 1.17.1.4 - MC 1.12.2        | Lycanites-Mobs-Mod-1.12.2.jar         | None                                     |
	| UC    | mantle                                       | 1.12-1.3.1.21               | Mantle-Mod-1.12.1.jar                 | None                                     |
	| UC    | roguelike                                    | 1.8.0                       | RoguelikeDungeons-1.12.2-1.8.0.jar    | None                                     |
	| UC    | tconstruct                                   | 1.12.2-2.10.1.87            | TConstruct-1.12.2-2.10.1.87.jar       | None                                     |
	| UC    | worldedit                                    | 6.1.8                       | worldedit-forge-mc1.12-6.1.8-dist.jar | None                                     |
	| UC    | flexiblelogin                                | 0.17.2                      | flexiblelogin-1.12.2-sponge.jar       | None                                     |
	| UC    | foxcore                                      |                             | foxcore-sponge-0.11.0-246.jar         | None                                     |
	| UE    | foxguard                                     |                             | foxguard-sponge-0.21.0-405.jar        | None                                     |

	Loaded coremods (and transformers): 
SpongeCoremod (spongeforge-1.12.2-forge.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
MovingWorldCore (MovingWorld-Mod-1.12.jar)
  
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)

**Comment by gravityfox** [comment]
What are the names of the FoxCore and FoxGuard jars that you have in the mods folder?

**Comment by Ziolo99** [comment]
I didn't change names. thay are same as downloaded from this site. foxguard-sponge-0.21.0-405.jar and foxcore-sponge-0.11.0-246.jar

**Comment by gravityfox** [comment]
You need to download the jars that say `-server.jar` at the end.

The jars without suffixes are development library jars and don't have all the classes shadowed in.
