### ISSUE TITLE
we have a little problem

### ISSUE THREAD

**Issue by terrainwax** [FoxDenStudio/FoxGuard#11]
All region of my server was delete i thinks it cause by that 

`````
[00:40:02] [Server thread/INFO] [com.zaxxer.hikari.HikariDataSource/]: HikariPool-0 - is starting.
[00:40:02] [Hikari connection adder (pool HikariPool-0)/DEBUG] [com.zaxxer.hikari.pool.HikariPool/]: HikariPool-0 - Cannot acquire connection from data source
org.h2.jdbc.JdbcSQLException: Database may be already in use: null. Possible solutions: close all other connection(s); use the server mode [90020-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345) ~[DbException.class:1.8-1577-3.0.0-BETA-1014]
	at org.h2.message.DbException.get(DbException.java:168) ~[DbException.class:1.8-1577-3.0.0-BETA-1014]
	at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:187) ~[MVTableEngine$Store.class:1.8-1577-3.0.0-BETA-1014]
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:167) ~[MVTableEngine$Store.class:1.8-1577-3.0.0-BETA-1014]
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:99) ~[MVTableEngine.class:1.8-1577-3.0.0-BETA-1014]
	at org.h2.engine.Database.getPageStore(Database.java:2450) ~[Database.class:1.8-1577-3.0.0-BETA-1014]
	at org.h2.engine.Database.open(Database.java:672) ~[Database.class:1.8-1577-3.0.0-BETA-1014]
	at org.h2.engine.Database.openDatabase(Database.java:269) ~[Database.class:1.8-1577-3.0.0-BETA-1014]
	at org.h2.engine.Database.<init>(Database.java:263) ~[Database.class:1.8-1577-3.0.0-BETA-1014]
	at org.h2.engine.Engine.openSession(Engine.java:65) ~[Engine.class:1.8-1577-3.0.0-BETA-1014]
	at org.h2.engine.Engine.openSession(Engine.java:175) ~[Engine.class:1.8-1577-3.0.0-BETA-1014]
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:153) ~[Engine.class:1.8-1577-3.0.0-BETA-1014]
	at org.h2.engine.Engine.createSession(Engine.java:136) ~[Engine.class:1.8-1577-3.0.0-BETA-1014]
	at org.h2.engine.Engine.createSession(Engine.java:28) ~[Engine.class:1.8-1577-3.0.0-BETA-1014]
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349) ~[SessionRemote.class:1.8-1577-3.0.0-BETA-1014]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107) ~[JdbcConnection.class:1.8-1577-3.0.0-BETA-1014]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91) ~[JdbcConnection.class:1.8-1577-3.0.0-BETA-1014]
	at org.h2.Driver.connect(Driver.java:72) ~[Driver.class:1.8-1577-3.0.0-BETA-1014]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95) ~[DriverDataSource.class:1.8-1577-3.0.0-BETA-1014]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:314) ~[PoolBase.class:1.8-1577-3.0.0-BETA-1014]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:171) ~[PoolBase.class:1.8-1577-3.0.0-BETA-1014]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:436) [HikariPool.class:1.8-1577-3.0.0-BETA-1014]
	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:65) [HikariPool.class:1.8-1577-3.0.0-BETA-1014]
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:567) [HikariPool$PoolEntryCreator.class:1.8-1577-3.0.0-BETA-1014]
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:560) [HikariPool$PoolEntryCreator.class:1.8-1577-3.0.0-BETA-1014]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_66]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.IllegalStateException: The file is locked: nio:/home/Serveur_Bungee/PokePixel/principale/foxguard/regions/_global.mv.db [1.4.190/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773) ~[DataUtils.class:1.8-1577-3.0.0-BETA-1014]
	at org.h2.mvstore.FileStore.open(FileStore.java:172) ~[FileStore.class:1.8-1577-3.0.0-BETA-1014]
	at org.h2.mvstore.MVStore.<init>(MVStore.java:342) ~[MVStore.class:1.8-1577-3.0.0-BETA-1014]
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2888) ~[MVStore$Builder.class:1.8-1577-3.0.0-BETA-1014]
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:154) ~[MVTableEngine$Store.class:1.8-1577-3.0.0-BETA-1014]
	... 25 more
````

**Comment by gravityfox** [comment]
idunno.

I don't have this issue.

**Comment by d4rkfly3r** [comment]
I managed to recreate this issue.  Upon the server crashing or being killed, it would throw this exception next run.  My guess is that the server never properly closed the connection when it was last turned off.  

Did the server crash recently?  If not do you have the log files from the time before it threw this exception?

**Comment by gravityfox** [comment]
What OS is this running on?

**Comment by terrainwax** [comment]
The server as crash cause pixelmon bug  and the os is debian 8

**Comment by gravityfox** [comment]
the database in question is in the stacktrace.

Can you go there and see if there is a lock file?

**Comment by terrainwax** [comment]
Ok

**Comment by terrainwax** [comment]
We have make a rollback we go to update after

**Comment by gravityfox** [comment]
Engrishplz?

**Comment by terrainwax** [comment]
oh sorry

**Comment by gravityfox** [comment]
Closing due to irreproducibility and inactivity.
