### ISSUE TITLE
Network Manager failing to lock before handshake.

### ISSUE THREAD

**Issue by jckani** [FoxDenStudio/FoxGuard#48]
1. 
/fg wand 
Server thread/ERROR [Sponge]: Error occurred while executing command 'fg wand' for source EntityPlayerMP['AHoshin']: No value present

2. 
Server thread/ERROR [foxcore]: Tried to negotiate handshake before manager configurations has been locked!

at server start

**Comment by gravityfox** [comment]
The first one has already been fixed.

I need a full server log to figure out the second.

**Comment by jckani** [comment]
But the fix hasnt been released yet ?

**Comment by gravityfox** [comment]
Yes, the fix has not been released yet.

I need those logs to fix the second issue, because the second issue is actually problematic.

**Comment by jckani** [comment]
22.10 00:23:31 [Server] Server thread/ERROR [foxcore]: Tried to negotiate handshake before manager configurations has been locked!
22.10 00:24:11 [Server] Server thread/INFO [io.github.hsyyid.essentialcmds]: [AHoshin] executed command fg wand
22.10 00:24:11 [Server] Server thread/ERROR [Sponge]: Error occurred while executing command 'fg wand' for source EntityPlayerMP['AHoshin'/1718, l='world', x=-591.89, y=69.00, z=-59.47]: No value present
22.10 00:24:11 [Server] INFO java.util.NoSuchElementException: No value present
22.10 00:24:11 [Server] INFO at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_92]
22.10 00:24:11 [Server] INFO at net.foxdenstudio.sponge.foxcore.plugin.command.CommandWand.process(CommandWand.java:88) ~[CommandWand.class:?]
22.10 00:24:11 [Server] INFO at net.foxdenstudio.sponge.foxcore.plugin.command.FCCommandDispatcher.process(FCCommandDispatcher.java:236) ~[FCCommandDispatcher.class:?]
22.10 00:24:11 [Server] INFO at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:331) ~[SimpleDispatcher.class:1.8.9-1890-4.2.0-BETA-1666]
22.10 00:24:11 [Server] INFO at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:279) [SpongeCommandManager.class:1.8.9-1890-4.2.0-BETA-1666]
22.10 00:24:11 [Server] INFO at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:80) [bd.class:?]
22.10 00:24:11 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:815) [lm.class:?]
22.10 00:24:11 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:794) [lm.class:?]
22.10 00:24:11 [Server] INFO at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ie.class:?]
22.10 00:24:11 [Server] INFO at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ie.class:?]
22.10 00:24:11 [Server] INFO at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:121) [PacketUtil.class:1.8.9-1890-4.2.0-BETA-1666]
22.10 00:24:11 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$0(SourceFile:39) [fh$1.class:?]
22.10 00:24:11 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fh$1.class:?]
22.10 00:24:11 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_92]
22.10 00:24:11 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_92]
22.10 00:24:11 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:44) [g.class:?]
22.10 00:24:11 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:660) [MinecraftServer.class:?]
22.10 00:24:11 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) [ko.class:?]
22.10 00:24:11 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) [MinecraftServer.class:?]
22.10 00:24:11 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
22.10 00:24:11 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]

Thats under the second error , if that helps

**Comment by jckani** [comment]
We really need world protection .. 

I created everything , handlers regions , flags, but players can still break blocks

**Comment by gravityfox** [comment]
No, I literally need the ENTIRE server log.

The problem is much further toward the beginning of the log.

**Comment by jckani** [comment]
[fml-server-3.txt](https://github.com/FoxDenStudio/FoxGuard/files/545415/fml-server-3.txt)

**Comment by gravityfox** [comment]
...

You're using the wrong version of the plugin.

You have MC 1.8.9

That is API 4

You grabbed the API5 version of the jar.

Really...
