### ISSUE TITLE
InteractBlockEvent Exception

### ISSUE THREAD

**Issue by Hodel1** [FoxDenStudio/FoxGuard#83]
Anything iteracting with, wil be replaced through dirt/gravel/stone.

```java
[22:11:26] [Server thread/ERROR] [Sponge/]: Could not pass InteractBlockEvent$Primary$MainHand$Impl to Plugin{id=foxguard, name=FoxGuard, version=0.20.5-untested-hotfix-367, description=A world protection plugin built for SpongeAPI. Requires FoxCore., url=https://github.com/FoxDenStudio/FoxGuard, authors=[gravityfox], source=/home/mcbeyond/beyond/./mods/plugins/foxguard-0.20.5-untested-hotfix-367-server.jar}
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_121]
	at net.foxdenstudio.sponge.foxguard.plugin.listener.InteractBlockListener.handle(InteractBlockListener.java:72) ~[InteractBlockListener.class:?]
	at net.foxdenstudio.sponge.foxguard.plugin.listener.InteractBlockListener.handle(InteractBlockListener.java:53) ~[InteractBlockListener.class:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-2281-5.2.0-BETA-2274]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:313) [SpongeModEventManager.class:1.10.2-2281-5.2.0-BETA-2274]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:297) [SpongeModEventManager.class:1.10.2-2281-5.2.0-BETA-2274]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:338) [SpongeModEventManager.class:1.10.2-2281-5.2.0-BETA-2274]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:326) [SpongeModEventManager.class:1.10.2-2281-5.2.0-BETA-2274]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:143) [SpongeImpl.class:1.10.2-2281-5.2.0-BETA-2274]
	at org.spongepowered.common.event.SpongeCommonEventFactory.callInteractBlockEventPrimary(SpongeCommonEventFactory.java:444) [SpongeCommonEventFactory.class:1.10.2-2281-5.2.0-BETA-2274]
	at org.spongepowered.common.network.PacketUtil.firePreEvents(PacketUtil.java:224) [PacketUtil.class:1.10.2-2281-5.2.0-BETA-2274]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:90) [PacketUtil.class:1.10.2-2281-5.2.0-BETA-2274]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjh000(SourceFile:539) [fl$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:241) [SpongeImplHooks.class:1.10.2-2281-5.2.0-BETA-2274]
	at net.minecraft.server.MinecraftServer.redirect$onRun$zhn000(MinecraftServer.java:3928) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

**Comment by ghost** [comment]
um wait what.... so the only way that could happen is if the block does not have a location.  what blocks where you interacting with, and do you have any mods installed? Please post a link to a gist or pastebin of the entire log.

**Comment by Hodel1** [comment]
It is based on FTB Beyond 1.5.3 (MC. 1.10.2), including Sponge 5.1 or 5.2, FoxGuard, Nucleus and a custom world plugin.

A player had clicked on any block and this got replaced randomly. i have a proof video.

**Comment by ghost** [comment]
can you get me the exact sponge version?

**Comment by Hodel1** [comment]
Yes, i know the version tomorrow surely.

**Comment by Hodel1** [comment]
We use Sponge api 5.2.0-20170315.160504-4

**Comment by ghost** [comment]
i'm just asking, will there be a foxguard/foxcore plugin for sponge 7.0.0 for minecraft 1.11.2 ? thanks.

**Comment by Hodel1** [comment]
Fixed after SpongeForge update.
