### ISSUE TITLE
Error during startup caused by MCStats

### ISSUE THREAD

**Issue by BrainStone** [FoxDenStudio/FoxGuard#85]
When the plugin starts this is the error I get:

```
[08:16:53] [pool-2-thread-1/ERROR] [Sponge]: The Scheduler tried to run the task foxguard-A-16 owned by Plugin{id=foxguard, name=FoxGuard, version=0.20.5-untested-hotfix-367, description=A world protection plugin built for SpongeAPI. Requires FoxCore., url=https://github.com/FoxDenStudio/FoxGuard, authors=[gravityfox], source=/opt/msm/servers/main/mods/foxguard-0.20.5-untested-hotfix-367-server.jar}, but an error occured.
java.lang.NoSuchMethodError: org.spongepowered.api.Platform.getImplementation()Lorg/spongepowered/api/plugin/PluginContainer;
        at net.minecrell.mcstats.SpongeStatsLite.getServerVersion(SpongeStatsLite.java:122) ~[SpongeStatsLite.class:?]
        at net.minecrell.mcstats.StatsLite.post(StatsLite.java:273) ~[StatsLite.class:?]
        at net.minecrell.mcstats.StatsLite.run(StatsLite.java:171) ~[StatsLite.class:?]
        at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.11.2-2282-7.0.0-BETA-2301]
        at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:187) ~[SchedulerBase.class:1.11.2-2282-7.0.0-BETA-2301]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

* Minecraft: 1.11.2
* FoxGurad: 0.20.5-untested-hotfix-367
* Sponge: spongeforge-1.11.2-2282-7.0.0-BETA-2301

**Comment by ghost** [comment]
Please see #82 - Both these issues go hand in hand, fixing that one, will in turn fix this.
