### ISSUE TITLE
Error When Launching the Server

### ISSUE THREAD

**Issue by TooVeryIcey** [FoxDenStudio/FoxGuard#98]
```
[19:42:06 ERROR] [Sponge]: Failed to load plugin: FoxGuard unknown (from mods/foxguard-sponge-0.21.0-405.jar)
com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: Lnet/minecrell/mcstats/SpongeStatsLite;
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2215) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.cache.LocalCache.get(LocalCache.java:4154) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153) ~[minecraft_server.1.12.2.jar:?]
        at com.google.inject.internal.FailableCache.get(FailableCache.java:48) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.ConstructorInjectorStore.get(ConstructorInjectorStore.java:50) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.ConstructorBindingImpl.initialize(ConstructorBindingImpl.java:138) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.InjectorImpl.initializeBinding(InjectorImpl.java:536) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.AbstractBindingProcessor$Processor$1.run(AbstractBindingProcessor.java:160) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.ProcessedBindingData.initializeBindings(ProcessedBindingData.java:44) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:123) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:232) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:236) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at org.spongepowered.server.plugin.VanillaPluginContainer.<init>(VanillaPluginContainer.java:43) ~[VanillaPluginContainer.class:1.12.2-7.1.0-BETA-33]
        at org.spongepowered.server.plugin.VanillaPluginManager.loadPlugin(VanillaPluginManager.java:165) ~[VanillaPluginManager.class:1.12.2-7.1.0-BETA-33]
        at java.util.ArrayList.forEach(ArrayList.java:1257) [?:1.8.0_162]
        at org.spongepowered.server.plugin.VanillaPluginManager.loadPlugins(VanillaPluginManager.java:88) [VanillaPluginManager.class:1.12.2-7.1.0-BETA-33]
        at org.spongepowered.server.SpongeVanilla.preInitialize(SpongeVanilla.java:118) [SpongeVanilla.class:1.12.2-7.1.0-BETA-33]
        at net.minecraft.server.dedicated.DedicatedServer.handler$onServerLoad$bac000(SourceFile:1234) [nz.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(SourceFile:117) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(SourceFile:434) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
Caused by: com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: Lnet/minecrell/mcstats/SpongeStatsLite;
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2215) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.cache.LocalCache.get(LocalCache.java:4154) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153) ~[minecraft_server.1.12.2.jar:?]
        at com.google.inject.internal.FailableCache.get(FailableCache.java:48) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.MembersInjectorStore.get(MembersInjectorStore.java:68) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.ConstructorInjectorStore.createConstructor(ConstructorInjectorStore.java:75) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.ConstructorInjectorStore.access$000(ConstructorInjectorStore.java:29) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:37) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:33) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.FailableCache$1.load(FailableCache.java:37) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) ~[minecraft_server.1.12.2.jar:?]
        ... 23 more
Caused by: java.lang.NoClassDefFoundError: Lnet/minecrell/mcstats/SpongeStatsLite;
        at java.lang.Class.getDeclaredFields0(Native Method) ~[?:1.8.0_162]
        at java.lang.Class.privateGetDeclaredFields(Class.java:2583) ~[?:1.8.0_162]
        at java.lang.Class.getDeclaredFields(Class.java:1916) ~[?:1.8.0_162]
        at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:675) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:380) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.MembersInjectorStore.createWithListeners(MembersInjectorStore.java:93) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.MembersInjectorStore.access$000(MembersInjectorStore.java:37) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:45) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:42) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.FailableCache$1.load(FailableCache.java:37) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.cache.LocalCache.get(LocalCache.java:4154) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153) ~[minecraft_server.1.12.2.jar:?]
        at com.google.inject.internal.FailableCache.get(FailableCache.java:48) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.MembersInjectorStore.get(MembersInjectorStore.java:68) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.ConstructorInjectorStore.createConstructor(ConstructorInjectorStore.java:75) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.ConstructorInjectorStore.access$000(ConstructorInjectorStore.java:29) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:37) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:33) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.FailableCache$1.load(FailableCache.java:37) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) ~[minecraft_server.1.12.2.jar:?]
        ... 23 more
Caused by: java.lang.ClassNotFoundException: net.minecrell.mcstats.SpongeStatsLite
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_162]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_162]
        at java.lang.Class.getDeclaredFields0(Native Method) ~[?:1.8.0_162]
        at java.lang.Class.privateGetDeclaredFields(Class.java:2583) ~[?:1.8.0_162]
        at java.lang.Class.getDeclaredFields(Class.java:1916) ~[?:1.8.0_162]
        at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:675) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:380) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.MembersInjectorStore.createWithListeners(MembersInjectorStore.java:93) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.MembersInjectorStore.access$000(MembersInjectorStore.java:37) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:45) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:42) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.FailableCache$1.load(FailableCache.java:37) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.cache.LocalCache.get(LocalCache.java:4154) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153) ~[minecraft_server.1.12.2.jar:?]
        at com.google.inject.internal.FailableCache.get(FailableCache.java:48) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.MembersInjectorStore.get(MembersInjectorStore.java:68) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.ConstructorInjectorStore.createConstructor(ConstructorInjectorStore.java:75) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.ConstructorInjectorStore.access$000(ConstructorInjectorStore.java:29) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:37) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:33) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.FailableCache$1.load(FailableCache.java:37) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) ~[minecraft_server.1.12.2.jar:?]
        ... 23 more
Caused by: java.lang.NullPointerException
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_162]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_162]
        at java.lang.Class.getDeclaredFields0(Native Method) ~[?:1.8.0_162]
        at java.lang.Class.privateGetDeclaredFields(Class.java:2583) ~[?:1.8.0_162]
        at java.lang.Class.getDeclaredFields(Class.java:1916) ~[?:1.8.0_162]
        at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:675) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:380) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.MembersInjectorStore.createWithListeners(MembersInjectorStore.java:93) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.MembersInjectorStore.access$000(MembersInjectorStore.java:37) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:45) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:42) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.FailableCache$1.load(FailableCache.java:37) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.cache.LocalCache.get(LocalCache.java:4154) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153) ~[minecraft_server.1.12.2.jar:?]
        at com.google.inject.internal.FailableCache.get(FailableCache.java:48) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.MembersInjectorStore.get(MembersInjectorStore.java:68) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.ConstructorInjectorStore.createConstructor(ConstructorInjectorStore.java:75) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.ConstructorInjectorStore.access$000(ConstructorInjectorStore.java:29) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:37) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:33) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.inject.internal.FailableCache$1.load(FailableCache.java:37) ~[spongevanilla-1.12.2-7.1.0-BETA-33.jar:1.12.2-7.1.0-BETA-33]
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) ~[minecraft_server.1.12.2.jar:?]
        ... 23 more
```

**Comment by gravityfox** [comment]
You used the development jar, which doesn't have any of the needed dependencies.

Please use the -server.jar file instead:
https://github.com/FoxDenStudio/FoxGuard-Sponge/releases/download/v0.21.0/foxguard-sponge-0.21.0-405-server.jar

**Comment by TooVeryIcey** [comment]
Oh! Sorry! Thanks!
